### ISSUE TITLE
Failed to load a language-agda package grammar

### ISSUE THREAD

**Issue by scmu** [banacorn/language-agda#10]
This happened after I tried to upgrade language-agda. Not sure whether it is a big issue. 

I uninstalled and reinstalled language-agda. During the installation I got an error message saying installation failed (with message "undefined"), but language-agda appeared to be installed anyway. Haven't tested it yet.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.11.6
**Thrown From**: [language-agda](https://github.com/banacorn/atom-language-agda) package 1.0.2

### Stack Trace

Failed to load a language-agda package grammar

```
At The module '/Users/scm/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/scm/.atom/packages/language-agda/grammars/tree-sitter-agda.cson

Error: The module '/Users/scm/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:2:20)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:11:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/src/tree-sitter-grammar.js:49:33)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/src/grammar-registry.js:494:20)
    at CSON.readFile (/Applications/Atom.app/Contents/Resources/app/src/grammar-registry.js:476:35)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:223:65
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
  at /packages/language-agda/grammars/tree-sitter-agda.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
agda-mode 0.7.12 
haskell-ghc-mod 2.2.3 
ide-haskell 2.3.1 
japanese-wrap 0.2.10 
language-agda 1.0.2 
language-haskell 1.17.8 
language-latex 1.1.1 
seti-syntax 1.1.3 
seti-ui 1.10.0 
```

**Comment by banacorn** [comment]
Atom underwent some update in version 1.28 that effects native bindings.
The latest patch should fix it :D
