### ISSUE TITLE
Failed to load a language-agda package grammar

### ISSUE THREAD

**Issue by eeoam** [banacorn/language-agda#20]
1. Error occurs immediately Atom is started up.

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 8
**Thrown From**: [language-agda](https://github.com/banacorn/atom-language-agda) package 1.0.9

### Stack Trace

Failed to load a language-agda package grammar

```
At A dynamic link library (DLL) initialisation routine failed.
\\?\C:\Users\Eric\.atom\packages\language-agda\node_modules\tree-sitter-agda\build\Release\tree_sitter_agda_binding.node in C:\Users\Eric\.atom\packages\language-agda\grammars\tree-sitter-agda.cson

Error: A dynamic link library (DLL) initialisation routine failed.
\\?\C:\Users\Eric\.atom\packages\language-agda\node_modules\tree-sitter-agda\build\Release\tree_sitter_agda_binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:146719)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:2:20)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:11:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:1:712926)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3463886)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:359235)
    at l.readFile (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:359076)
    at ~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:580572
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
  at /packages/language-agda/grammars/tree-sitter-agda.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
agda-mode 0.9.0 
atom-ide-ui 0.13.0 
build 0.70.0 
busy-signal 1.4.3 
hyperclick 0.0.0 
ide-purescript 0.25.0 
language-agda 1.0.9 
language-purescript 0.9.0 
platformio-ide-terminal 2.8.4 
project-plus 1.0.0 
```

**Comment by banacorn** [comment]
Thank you for reporting this.
But I have no idea what is going on.
Seem like many other people are also facing the same problem recently.
https://github.com/tree-sitter/tree-sitter/issues/385#issuecomment-515511715

**Comment by fwcd** [comment]
Try rebuilding the package. First open the panel with incompatible packages by clicking the bug in the status bar:

![grafik](https://user-images.githubusercontent.com/30873659/62816106-ad29f100-bb22-11e9-9b1b-6f78dd946f3a.png)

Then click `Rebuild`.

**Comment by banacorn** [comment]
I have rewritten the whole parser from scratch, please update to `v1.2.0` to see if it works!
