### ISSUE TITLE
Failed to load a language-agda package grammar

### ISSUE THREAD

**Issue by BekaValentine** [banacorn/language-agda#21]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [language-agda](https://github.com/banacorn/atom-language-agda) package 1.0.9

### Stack Trace

Failed to load a language-agda package grammar

```
At The module '/Users/beka/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/beka/.atom/packages/language-agda/grammars/tree-sitter-agda.cson

Error: The module '/Users/beka/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:2:20)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:11:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3217918)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359778)
    at l.readFile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359619)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:581565
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
  at /packages/language-agda/grammars/tree-sitter-agda.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
agda-mode 0.9.7 
ide-python 1.4.2 
language-agda 1.0.9 
language-ql 1.0.2 
```

**Comment by glangmead** [comment]
me too

**Comment by banacorn** [comment]
Oh no sorry somehow I missed the notification of this issue!
I'll look into this ASAP

**Comment by lemastero** [comment]
1. apply buff that grants you immunity to mind control magic like fear, sleep, doubt, etc (listening to Fear of the Dark, by Iron Maiden workes for me)
2. uninstall your Atom plugins for Agda
3. install your Atom plugins for Agda
4. enjoy brave new world :)

**Comment by banacorn** [comment]
I have rewritten the whole parser from scratch, please update to `v1.2.0` to see if it works!
