### ISSUE TITLE
Failed to load a language-agda package grammar

### ISSUE THREAD

**Issue by marnen** [banacorn/language-agda#22]
[Enter steps to reproduce:]

This happened while launching Atom immediately after upgrading Mac OS from 10.14.5 to 10.14.6.

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [language-agda](https://github.com/banacorn/atom-language-agda) package 1.0.9

### Stack Trace

Failed to load a language-agda package grammar

```
At The module '/Users/marnen/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/marnen/.atom/packages/language-agda/grammars/tree-sitter-agda.cson

Error: The module '/Users/marnen/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:2:20)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:11:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3217918)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359778)
    at l.readFile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359619)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:581565
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
  at /packages/language-agda/grammars/tree-sitter-agda.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
ABC-notation 1.0.1 
agda-mode 0.9.7 
aligner 1.2.4 
aligner-css 1.2.1 
aligner-gherkin 0.0.1 
aligner-javascript 1.3.0 
andika 0.1.2 
AtLilyPond 1.2.2 
borodin 0.0.1 
atom-elixir 0.2.3 
atom-ide-ui 0.13.0 
atom-unsaved-changes 0.4.0 
busy-signal 2.0.1 
coffee-compile 0.32.0 
cucumber 0.7.0 
foldername-tabs 0.2.4 
font-viewer 0.3.1 
fonts 3.1.0 
git-control 0.9.0 
git-log 0.4.1 
git-plus 8.7.1 
git-tab-status 1.9.2 
git-tabs 0.4.1 
haskell-pointfree 0.2.0 
hey-pane 1.2.0 
ide-elixir 0.2.25 
ide-haskell 2.4.0 
ide-haskell-cabal 2.2.1 
ide-haskell-repl 0.8.7 
indent-toggle-on-paste 0.1.3 
intentions 1.1.5 
language-agda 1.0.9 
language-babel 2.85.0 
language-bbcode 0.1.1 
language-docker 1.1.8 
language-elixir 0.22.1 
language-erlang 3.2.0 
language-haml 0.32.1 
language-haskell 1.19.1 
language-javascript-better 1.7.1 
language-liquid 0.7.0 
language-lisp 0.2.0 
language-opentype 0.4.1 
language-rust 0.4.12 
language-shakespeare 0.2.2 
language-svg 0.9.2 
language-vue 0.25.0 
linter 2.3.1 
linter-docker 0.3.2 
linter-ui-default 1.8.0 
markdown-table-formatter 2.9.2 
merge-conflicts 1.4.5 
monokai 0.24.0 
package-cop 0.2.10 
package-switch 0.5.0 
pdf-view 0.72.0 
pigments 0.40.2 
preview 0.19.0 
process-palette 0.17.0 
project-manager 3.3.7 
regex-railroad-diagram 0.19.4 
revert-buffer 0.6.0 
ruby-slim 0.2.0 
simple-align 0.2.0 
source-preview 0.5.3 
Sublime-Style-Column-Selection 1.7.5 
svg-preview 0.14.0 
tablr 1.8.3 
```

**Comment by marnen** [comment]
Possible duplicate of #21.

**Comment by banacorn** [comment]
I have rewritten the whole parser from scratch, please update to `v1.2.0` to see if it works!

**Comment by marnen** [comment]
@banacorn Thanks! I’ll try upgrading and reopen if the error persists.
