### ISSUE TITLE
Failed to load a language-agda package grammar

### ISSUE THREAD

**Issue by banacorn** [banacorn/language-agda#23]
Here we go again...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [language-agda](https://github.com/banacorn/atom-language-agda) package 1.2.0

### Stack Trace

Failed to load a language-agda package grammar

```
At The module '/Users/banacorn/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/banacorn/.atom/packages/language-agda/grammars/tree-sitter-agda.cson

Error: The module '/Users/banacorn/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/banacorn/github/language-agda/node_modules/tree-sitter-agda/index.js:2:20)
    at Object.<anonymous> (/Users/banacorn/github/language-agda/node_modules/tree-sitter-agda/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688212)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3131248)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360047)
    at l.readFile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359888)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:581849
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
  at /packages/language-agda/grammars/tree-sitter-agda.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
agda-mode 0.9.9 
atom-ide-ui 0.13.0 
gcl-atom 0.0.0 
ide-haskell 2.4.1 
ide-reason 1.1.11 
language-agda 1.2.0 
language-haskell 1.19.1 
language-ocaml 1.9.5 
language-reason 0.0.5 
```

**Comment by banacorn** [comment]
For posterity:

If you are bumping into this again, probably after updating Atom. 
Please uninstall and reinstall `language-agda` and everything should be fine.
