### ISSUE TITLE
Failed to load a language-agda package grammar

### ISSUE THREAD

**Issue by jaiyalas** [banacorn/language-agda#25]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.12.6
**Thrown From**: [language-agda](https://github.com/banacorn/atom-language-agda) package 1.2.0

### Stack Trace

Failed to load a language-agda package grammar

```
At The module '/Users/jaiyalas/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/jaiyalas/.atom/packages/language-agda/grammars/tree-sitter-agda.cson

Error: The module '/Users/jaiyalas/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:2:20)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688212)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3131248)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360047)
    at l.readFile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359888)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:581849
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
  at /packages/language-agda/grammars/tree-sitter-agda.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
agda-mode 0.9.9 
atom-ide-ui 0.13.0 
atom-terminal 0.8.0 
autocomplete-haskell 1.0.1 
city-lights-syntax 1.1.8 
draw-package 0.1.2 
file-icons 2.1.35 
haskell-pointfree 0.2.0 
highlight-selected 0.16.0 
ide-json 0.2.1 
ide-reason 1.1.11 
jackhammer-syntax 1.1.0 
language-agda 1.2.0 
language-elm 1.5.0 
language-haskell 1.19.1 
language-haskell-scoped 0.1.1 
language-latex 1.2.0 
language-markdown 0.37.0 
language-ocaml 1.9.5 
language-reason 0.0.5 
language-renpy 2.5.0 
language-rust 0.4.12 
latex 0.50.2 
markdown-preview-enhanced 0.16.3 
markdown-table-editor 1.1.2 
markdown-themeable-pdf 1.2.1 
markdown-writer 2.11.9 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
nord-atom-syntax 0.10.0 
nord-atom-ui 0.12.0 
nordkind-dark-syntax 0.6.0 
ocaml-merlin 0.14.7 
package-list 0.1.2 
pdf-view 0.72.0 
pure-syntax 1.0.1 
remote-ftp 2.2.2 
remote-sync 4.1.8 
rst-preview 1.3.1 
split-diff 1.6.1 
styri-syntax 1.0.0 
Sublime-Style-Column-Selection 1.7.5 
svg-preview 0.14.0 
tablr 1.8.3 
tree-sitter-syntax-visualizer 0.0.2 
twilight-syntax 0.8.0 
```

plz... QQ

**Comment by banacorn** [comment]
Please **uninstsall** and then **reinstall** the package and the problem should go away
