### ISSUE TITLE
Failed to load a language-agda package grammar

### ISSUE THREAD

**Issue by junewunder** [banacorn/language-agda#26]
[Enter steps to reproduce:]

1. Open Atom
2. Get issue popping up

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: [language-agda](https://github.com/banacorn/atom-language-agda) package 1.2.0

### Stack Trace

Failed to load a language-agda package grammar

```
At The module '/Users/jacob/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/jacob/.atom/packages/language-agda/grammars/tree-sitter-agda.cson

Error: The module '/Users/jacob/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:2:20)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688212)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3131248)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360047)
    at l.readFile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359888)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:581849
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
  at /packages/language-agda/grammars/tree-sitter-agda.cson:1:1
```

### Commands

```
     -0:27.3.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
agda-mode 0.9.10 
atom-ide-racket 0.3.0 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-mermaid 3.4.1 
atom-ternjs 0.20.0 
uhh 0.1.0 
autocomplete-clang 0.12.1 
autocomplete-java 1.2.7 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
chester-atom-syntax 0.3.2 
clipboard-plus 0.5.1 
color-picker 2.3.0 
emmet 2.4.3 
file-type-icons 1.3.4 
file-types 1.0.1 
ide-cpp 0.1.0 
ide-css 0.3.3 
ide-haskell 2.4.1 
ide-haskell-cabal 2.3.0 
ide-haskell-hoogle 0.1.2 
ide-java 0.9.0 
ide-php 0.7.18 
ide-reason 1.1.11 
ide-rust 0.21.1 
ide-typescript 0.9.1 
intentions 1.1.5 
language-agda 1.2.0 
language-haskell 1.19.1 
language-javascript-jsx 0.3.7 
language-lisp 0.2.0 
language-ocaml 1.9.5 
language-racket 0.4.0 
language-reason 0.0.5 
language-rust 0.4.12 
latex-completions 0.3.6 
linter 2.3.1 
linter-eslint 8.5.5 
linter-hdevtools 1.10.0 
linter-javac 1.10.0 
linter-jshint 3.1.17 
linter-php 1.6.1 
linter-pycodestyle 2.1.3 
linter-rst 2.0.0 
linter-ui-default 1.8.0 
mcfunction 0.6.4 
merge-conflicts 1.4.5 
minimap 4.29.9 
multi-cursor 3.0.0 
pigments 0.40.2 
print-code 0.7.1 
pure-syntax 1.0.1 
react 0.18.0 
reason-refmt 0.3.3 
remote-ftp 2.2.2 
script 3.25.0 
Stylus 3.2.0 
tablr 1.8.3 
teletype 0.13.4 
```

**Comment by banacorn** [comment]
Please **uninstsall** and then **reinstall** and the problem should go away

**Comment by junewunder** [comment]
thank you :)
