### ISSUE TITLE
Failed to load a language-agda package grammar

### ISSUE THREAD

**Issue by nikoloz-pachuashvili** [banacorn/language-agda#31]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [language-agda](https://github.com/banacorn/atom-language-agda) package 1.2.0

### Stack Trace

Failed to load a language-agda package grammar

```
At The specified module could not be found.
\\?\C:\Users\n.pachuashvili\.atom\packages\language-agda\node_modules\tree-sitter-agda\build\Release\tree_sitter_agda_binding.node in C:\Users\n.pachuashvili\.atom\packages\language-agda\grammars\tree-sitter-agda.cson

Error: The specified module could not be found.
\\?\C:\Users\n.pachuashvili\.atom\packages\language-agda\node_modules\tree-sitter-agda\build\Release\tree_sitter_agda_binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:2:20)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:15:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:1:721712)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3249210)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:359945)
    at l.readFile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:359786)
    at ~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:581672
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
  at /packages/language-agda/grammars/tree-sitter-agda.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
agda-mode 0.9.10 
language-agda 1.2.0 
language-idris 0.5.0 
proto-repl 1.4.24 
```

**Comment by banacorn** [comment]
Please **uninstsall** and then **reinstall** and see what happens
