### ISSUE TITLE
Failed to load a language-agda package grammar

### ISSUE THREAD

**Issue by Dsolnik** [banacorn/language-agda#34]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Pop!_OS 20.04
**Thrown From**: [language-agda](https://github.com/banacorn/atom-language-agda) package 1.2.0

### Stack Trace

Failed to load a language-agda package grammar

```
At The module '/home/daniel/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /home/daniel/.atom/packages/language-agda/grammars/tree-sitter-agda.cson

Error: The module '/home/daniel/.atom/packages/language-agda/node_modules/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146766)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:2:20)
    at /packages/language-agda/node_modules/tree-sitter-agda/index.js:15:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695413)
    at new TreeSitterGrammar (/usr/share/atom/resources/app/static/<embedded>:11:3114299)
    at GrammarRegistry.createGrammar (/usr/share/atom/resources/app/static/<embedded>:11:360231)
    at /usr/share/atom/resources/app/static/<embedded>:11:360072
    at /usr/share/atom/resources/app/static/<embedded>:11:581958
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
  at /packages/language-agda/grammars/tree-sitter-agda.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
language-agda 1.2.0 
```

**Comment by josephcsible** [comment]
The trigger for this seems to have been upgrading Atom to 1.47.0. I'm guessing the particular change responsible was switching to Electron 5.
